[package]
name = "jrpc-types"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4.27", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"

[features]
default = ["log"]
log = ["dep:log"]
